name: build-test
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - .gitignore
      - .editorconfig
  pull_request:
    paths-ignore:
      - '**.md'
      - .gitignore
      - .editorconfig
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '~1.17.5'
      - name: Go Version Check
        run: go version
      - name: Install linter
        run: |
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build .
      - name: Run linter
        run: |
          go vet .
          golint .
      - name: Run tests
        run: go test -covermode=atomic ./...
      - name: Build
        run: GOOS=linux go build -ldflags="-s -w"
      - name: Run
        run: ./adventofcode2021
